app/auth.py
from flask import render_template, redirect, request, url_for, flash, Blueprint, session
from flask_login import login_user, logout_user, login_required, current_user
from .models import db, User
from werkzeug.security import generate_password_hash
from .forms import LoginForm, RegistrationForm, PasswordResetRequestForm, PasswordResetForm
auth = Blueprint('auth', __name__)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('views.home')
            return redirect(next)
        flash('Invalid username or password.')
    return render_template('auth/login.html', form=form)
        

@auth.route('/logout')
@login_required
def logout():
    #logout_user()
    session.clear()
    flash('You have been logged out.')
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('You can now log in')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


# this function is called when 

# @auth.route('/reset', methods=['GET', 'POST'])
# def password_reset_request():
#     if not current_user.is_anonymous:
#         return redirect(url_for('main.index'))
#     form = PasswordResetRequestForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(username=form.username.data).first()
#         if user:
#             return redirect(url_for('auth.password_reset'))
#     return render_template('auth/login.html')

@auth.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            return redirect(url_for('auth.password_reset', user_id=user.id))
        else:
            flash('User not found.', 'danger')
            return(redirect(url_for('auth.login')))
    return render_template('auth/reset_password.html', form =form)


# @auth.route('/reset/<int:user_id>', methods=['GET', 'POST'])
# def password_reset():
#     if not current_user.is_anonymous:
#          return redirect(url_for('main.index'))
#     form = PasswordResetForm()
#     if form.validate_on_submit():
#         if User.reset_password(form.password.data):
#             db.session.commit()
#             flash('Your password has been updated.')
#             return redirect(url_for('auth.login'))
#         else:
#             return redirect(url_for('main.index'))
#     return render_template('auth/reset_password.html', form=form)

@auth.route('/reset/<int:user_id>', methods=['GET', 'POST'])
def password_reset(user_id):
    user = User.query.get(user_id)
    if not user:
         flash('User not found.', 'danger')
         return redirect(url_for('auth.login'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        db.session.add(current_user)
        db.session.commit()
        flash('Password reset successful.', 'success')
        return redirect(url_for('auth.login'))
    return render_template('auth/reset_password.html', form=form)

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from .forms import StudentAdmissionForm, HODRegistrationForm, StaffRegistrationForm, TeacherRegistrationForm
from . import mysql_conn

bp = Blueprint('views', __name__)


@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return redirect(url_for('auth.login'))

@bp.route('/cchs', methods=['GET', 'POST'])
@login_required
def home():
    return render_template('index.html')

@bp.route('/cchs/student_registration', methods=['GET', 'POST'])
@login_required
def register_student():
    form = StudentAdmissionForm()
    if request.method == "POST" and form.validate_on_submit():
        first_name = form.first_name.data.title()
        last_name = form.last_name.data.title()
        dob = form.dob.data
        blood_group = form.blood_group.data.upper()
        genotype = form.genotype.data.upper()
        religion = form.religion.data
        address = form.address.data
        phone = form.phone.data
        ethnicity = form.ethnicity.data.title()
        city_town = form.city_town.data.title()
        medical = form.medical.data
        class_id = int(form.class_id.data)

        if medical.strip(" ") == "":
            medical = None 

        # save to MySQL database
        # check database connection
        try:
            cur = mysql_conn.connection.cursor()
        except:
            flash("Unable to connect to database. Check database credentials in __init__.py")

        # check calling the stored procedure 
        try:
            cur.callproc('register_student', 
                  [first_name, last_name, dob, blood_group, genotype, religion, address,
                    phone, ethnicity, city_town, medical, class_id])
            mysql_conn.connection.commit()
            cur.close()
            flash('Sucessfully registered')
        except:
            flash("Error in calling procedure")

        return redirect(url_for('views.register_student'))

    return render_template('registrationform.html', form=form)


@bp.route('/cchs/HOD_registration', methods=['GET', 'POST'])
@login_required
def register_hod():
    form = HODRegistrationForm() 
    if request.method == "POST" and form.validate_on_submit():
        id = int(form.id.data)
        first_name = form.first_name.data.title()
        last_name = form.last_name.data.title()
        dob = form.dob.data
        blood_group = form.blood_group.data.upper()
        genotype = form.genotype.data.upper()
        religion = form.religion.data
        address = form.address.data
        phone = form.phone.data
        s_phone = form.s_phone.data
        ethnicity = form.ethnicity.data.title()
        city_town = form.city_town.data.title()
        medical = form.medical.data
        bonus = form.bonus.data
        dept_id = int(form.dept_id.data)

        if medical.strip(" ") == "":
            medical = None 

        if s_phone.strip(" ") == "":
            s_phone = None

        if bonus.strip(" ") == "":
            bonus = None

         # save to MySQL database
         # check database connection
        try:
            cur = mysql_conn.connection.cursor()
        except:
            flash("Unable to connect to database. Check database credentials in __init__.py")

        # check calling the stored procedure
        try:
            cur.callproc('register_hod', 
                  [id, first_name, last_name, dob, blood_group, genotype, religion, address,
                    phone, s_phone, ethnicity, city_town, medical, bonus, dept_id])
            mysql_conn.connection.commit()
            cur.close()
            flash('Sucessfully registered')
        except:
            flash("Error in calling procedure")


        return redirect(url_for('views.register_hod'))

    return render_template('registrationform.html', form=form)


@bp.route('/cchs/staff_registration', methods=['GET', 'POST'])
@login_required
def register_staff():
    form = StaffRegistrationForm() 
    if request.method == "POST" and form.validate_on_submit():
        id = int(form.id.data)
        first_name = form.first_name.data.title()
        last_name = form.last_name.data.title()
        dob = form.dob.data
        blood_group = form.blood_group.data.upper()
        genotype = form.genotype.data.upper()
        religion = form.religion.data
        address = form.address.data
        phone = form.phone.data
        s_phone = form.s_phone.data
        ethnicity = form.ethnicity.data.title()
        city_town = form.city_town.data.title()
        medical = form.medical.data
        bonus = form.bonus.data
        dept_id = form.dept_id.data 

        # Inserting nulls into the database for blank attributes instead of whitespace for easier querying
        if medical.strip(" ") == "":
            medical = None 

        if s_phone.strip(" ") == "":
            s_phone = None

        if bonus.strip(" ") == "":
            bonus = None

         # save to MySQL database
         # check database connection
        try:
            cur = mysql_conn.connection.cursor()
        except:
            flash("Unable to connect to database. Check database credentials in __init__.py")

        # check calling the stored procedure
        try:
            cur.callproc('register_staff', 
                  [id, first_name, last_name, dob, blood_group, genotype, religion, address,
                    phone, s_phone, ethnicity, city_town, medical, bonus, dept_id])
            mysql_conn.connection.commit()
            cur.close()
            flash('Sucessfully registered')
        except:
            flash("Error in calling procedure")


        return redirect(url_for('views.register_staff'))

    return render_template('registrationform.html', form=form)


@bp.route('/cchs/teaching_staff_registration', methods=['GET', 'POST'])
@login_required
def register_teacher():
    form = TeacherRegistrationForm()
    if request.method == "POST" and form.validate_on_submit():
        id = int(form.id.data)
        first_name = form.first_name.data.title()
        last_name = form.last_name.data.title()
        dob = form.dob.data
        blood_group = form.blood_group.data.upper()
        genotype = form.genotype.data.upper()
        religion = form.religion.data
        address = form.address.data
        phone = form.phone.data
        s_phone = form.s_phone.data
        ethnicity = form.ethnicity.data.title()
        city_town = form.city_town.data.title()
        medical = form.medical.data
        bonus = form.bonus.data
        dept_id = form.dept_id.data 

        # Inserting nulls into the database for blank attributes instead of whitespace for easier querying
        if medical.strip(" ") == "":
            medical = None 

        if s_phone.strip(" ") == "":
            s_phone = None

        if bonus.strip(" ") == "":
            bonus = None

         # save to MySQL database
         # check database connection
        try:
            cur = mysql_conn.connection.cursor()
        except:
            flash("Unable to connect to database. Check database credentials in __init__.py")

        # check calling the stored procedure
        try:
            cur.callproc('register_teacher', 
                  [id, first_name, last_name, dob, blood_group, genotype, religion, address,
                    phone, s_phone, ethnicity, city_town, medical, bonus, dept_id])
            mysql_conn.connection.commit()
            cur.close()
            flash('Sucessfully registered')
        except:
            flash("Error in calling procedure")


        return redirect(url_for('views.register_teacher'))

    return render_template('registrationform.html', form=form)


@bp.route('/cchs/search', methods=['GET', 'POST'])
@login_required
def search():
    cur = mysql_conn.connection.cursor()
    if request.method == "POST":
        search_query = request.form["search_query"]

        # if search_query == " ":
        #     query = """
        #     SELECT * FROM person;
        #     """
        #     cur.execute(query)
        #     persons = cur.fetchall()
        #     cur.close()

            #query = "SELECT * FROM person WHERE person_id LIKE "%{}%" OR first_name LIKE "%{}%" OR last_name LIKE "%{}%" OR phone LIKE "%{}%";",('%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%', '%' + search_query + '%')
        
        query = "SELECT * FROM person WHERE person_id LIKE '%{}%' OR first_name LIKE '%{}%' OR last_name LIKE '%{}%' OR phone LIKE '%{}%'".format(search_query, search_query, search_query, search_query)
        cur.execute(query)
        persons = cur.fetchall()
        #print(persons)
        cur.close()

        return render_template('search.html', persons=persons)
    return render_template('search.html')






    

app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

app/templates/base.html


{% block head %}

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}


{% block navbar %}
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{ url_for('views.home') }}" class="nav-link px-2 text-white">Home</a></li>
  
        </ul>

        {% if current_user.is_authenticated %}
        <div class="text-end">
            <a href="{{ url_for('auth.password_reset_request') }}"><button type="button" class="btn btn-outline-light me-2">Change Password</button></a>
            <a href="{{ url_for('auth.logout') }}""><button type="button" class="btn btn-warning">Log Out</button></a>
            {% else %}
<a href="{{ url_for('auth.login') }}"><button type="button" class="btn btn-outline-light me-2">Log in</button></a>
{% endif %}
          
        </div>
      </div>
    </div>
  </header>
  
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>

{% endblock %}

app/templates/index.html

{% extends "base.html" %}
{% block page_content %}

<div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <div class="feature-icon bg-primary bg-gradient">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32"  viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        </div>
        <h2>Register Student</h2>
        <p>For students only</p>
        <a href="{{ url_for('views.register_student') }}" class="icon-link">
          Click to register
        
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon bg-primary bg-gradient">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32"  viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        </div>
        <h2>Register HOD</h2>
        <p>For Heads of Department only</p>
        <a href="{{ url_for('views.register_hod') }}" class="icon-link">
          Click to register
         
        </a>
      </div>
      <div class="feature col">
        <div class="feature-icon bg-primary bg-gradient">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32"  viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        </div>
        <h2>Register Staff</h2>
        <p>For non-teaching staff only</p>
        <a href="{{ url_for('views.register_staff') }}" class="icon-link">
          Click to register
        </a>
      </div>

      <div class="feature col">
        <div class="feature-icon bg-primary bg-gradient">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32"  viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>

        </div>
        <h2>Register Teacher</h2>
        <p>For teachers only</p>
        <a href="{{ url_for('views.register_teacher') }}" class="icon-link">
          Click to register
         
        </a>
      </div>

      <div class="feature col">
        <div class="feature-icon bg-primary bg-gradient">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32"  viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>

        </div>
        <h2>Search</h2>
        <p>Search for personnel by name, phone number ...</p>
        <a href="{{ url_for('views.search') }}" class="icon-link">
          Click to search
        </a>
      </div>
    </div>
  </div>

  {% endblock %}

  {% block scripts %}
{{ super() }}

{% endblock %}

app/templates/registrationform.html
{% extends "base.html" %}
{% block page_content %}

{% from "_formhelpers.html" import render_field %}
<form method="POST">
    <dl class="col-5">
        {{ form.hidden_tag() }}
        {% if form.id %}
        {{ render_field(form.id, class="form-control") }}
        {% endif %}

        {{ render_field(form.first_name, class="form-control") }}
        {{ render_field(form.last_name, class="form-control") }}
        {{ render_field(form.dob, class="form-control") }}
        {{ render_field(form.blood_group, class="form-control") }}
        {{ render_field(form.genotype, class="form-control") }}
        {{ render_field(form.religion, class="form-control", placeholder="Choose...") }}
        {{ render_field(form.address, class="form-control") }}
        {{ render_field(form.phone, class="form-control") }}

        {% if form.s_phone%}
        {{ render_field(form.s_phone, class="form-control") }}
        {% endif %}

        {{ render_field(form.ethnicity, class="form-control") }}
        {{ render_field(form.city_town, class="form-control") }}
        {{ render_field(form.medical, class="form-control") }}

        {% if form.bonus %}
        {{ render_field(form.bonus, class="form-control") }}
        {% endif %}

        {% if form.dept_id %}
        {{ render_field(form.dept_id, class="form-control") }}
        {% endif %}

        {% if form.class_id %}
        {{ render_field(form.class_id, class="form-control") }}
        {% endif %}


    </dl>
    <p><input type="submit" value="Register"></p>
</form>

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}


app/templates/search.html
{% extends "base.html" %}
{% block page_content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary mt-5">
    <div class="container-fluid">
     
      <div class="collapse navbar-collapse" id="navbarSupportedContent2">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Search on ID, first name, last name or phone number</a>
          </li>
          
        </ul>
       

        <form class="d-flex my-auto" method="post">
            
            <input  class="form-control me-2" name="search_query" id="search_query" placeholder="Search" required>
            <button class="btn btn-outline-light" type="submit">Query</button>
        </form>
      </div>
    </div>
  </nav>





{% if persons %}
<h2>Search Results:</h2>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Date of Birth</th>
            <th scope="col">Blood Group</th>
            <th scope="col">Genotype</th>
            <th scope="col">Religion</th>
            <th scope="col">Town</th>
            <th scope="col">Spouse Number</th>
        </tr>
    </thead>

    <tbody>
        {% for person in persons %}
        <tr>
            <th scope="row">
            {% for item in person[:9] %}
            <td>{{ item }}</td>
            {% endfor %}
        </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock %}

app/templates/t_test.html
{% extends "base.html" %}
{% block page_content %}

<h1>test</h1>
{% for item in form%}
{{ item }}
{% endfor %}

{% endblock %}